import os
from supabase import create_client, Client
from ..config import settings
from ..models import Ticket, TestCase, TestResult, TestRun

class SupabaseClient:
    def __init__(self):
        url: str = settings.SUPABASE_URL
        key: str = settings.SUPABASE_SECRET_KEY
        if not url or not key:
            print("Warning: Supabase credentials not found in environment")
            self.client = None
        else:
            self.client: Client = create_client(url, key)

    def insert_ticket(self, ticket: Ticket):
        if not self.client: return None
        return self.client.table('tickets').insert(ticket.model_dump(mode='json')).execute()

    def upsert_ticket(self, ticket: Ticket):
        """Insert ticket, silently ignore if it already exists (same id)."""
        if not self.client: return None
        try:
            return self.client.table('tickets').upsert(
                ticket.model_dump(mode='json'), on_conflict='id'
            ).execute()
        except Exception as e:
            print(f"Warning: could not upsert ticket {ticket.id}: {e}")

    def insert_test_case(self, test_case: TestCase):
        if not self.client: return None
        # exclude_none so optional columns absent from the DB schema aren't sent
        # exclude source_test_id since it's only used in memory for spreadsheet updates
        data = test_case.model_dump(mode='json', exclude_none=True, exclude={'source_test_id'})
        return self.client.table('test_cases').insert(data).execute()

    def get_test_cases_by_ticket_id(self, ticket_id: str) -> list[TestCase]:
        """Return all test cases previously generated for a given source/ticket ID."""
        if not self.client:
            return []
        try:
            resp = self.client.table('test_cases').select('*').eq('ticket_id', ticket_id).execute()
            return [TestCase(**row) for row in (resp.data or [])]
        except Exception as e:
            print(f"Warning: could not query existing test cases: {e}")
            return []

    def create_test_run(self, total_tests: int) -> str:
        """Create a new test run and return its ID"""
        if not self.client: return "mock-run-id"
        run = TestRun(id="mock-run-id", total_tests=total_tests) # UUID is generated by DB if left blank, but pydantic requires it. We should let DB generate.
        # Let's adjust to let DB generate id or generate UUID here
        import uuid
        run_id = str(uuid.uuid4())
        run = TestRun(id=run_id, total_tests=total_tests)
        self.client.table('test_runs').insert(run.model_dump(mode='json')).execute()
        return run_id
        
    def update_test_run(self, run_id: str, passed: int, failed: int, duration: float, cost: float, status: str = 'completed'):
        if not self.client: return None
        import datetime
        return self.client.table('test_runs').update({
            'passed': passed,
            'failed': failed,
            'duration_seconds': duration,
            'api_cost_usd': cost,
            'status': status,
            'completed_at': datetime.datetime.utcnow().isoformat() if status == 'completed' else None
        }).eq('id', run_id).execute()

    def insert_test_result(self, result: TestResult):
        if not self.client: return None
        return self.client.table('test_results').insert(result.model_dump(mode='json', exclude={'cost'})).execute()

    def get_results_for_run(self, run_id: str) -> list[TestResult]:
        if not self.client: return []
        try:
            resp = self.client.table('test_results').select('*').eq('test_run_id', run_id).execute()
            return [TestResult(**row) for row in (resp.data or [])]
        except Exception as e:
            print(f"Warning: could not query results for run {run_id}: {e}")
            return []

    def upload_screenshot(self, file_path: str, file_name: str) -> str:
        """Upload a screenshot to Supabase Storage and return the public URL"""
        if not self.client: return "https://mock-url.com/screenshot.png"
        with open(file_path, 'rb') as f:
            self.client.storage.from_('screenshots').upload(
                file=f,
                path=file_name,
                file_options={"content-type": "image/png"}
            )
        return self.client.storage.from_('screenshots').get_public_url(file_name)
